from tkinter import *
from PIL import ImageTk,Image

root=Tk()
root.title("Keyboard")
root.geometry("667x178")

e=Entry(root,width=82,borderwidth=5)
e.grid(row=0,column=0)

frame1=Frame(root,width=800,height=100)
frame2=Frame(root,width=600,height=100)
frame3=Frame(root,width=800,height=100)
frame4=Frame(root,width=800,height=100)
frame5=Frame(root,width=800,height=100)

frame1.grid(row=1,column=0)
frame2.grid(row=2,column=0)
frame3.grid(row=3,column=0)
frame4.grid(row=4,column=0)
frame5.grid(row=5,column=0)

img=ImageTk.PhotoImage(Image.open("windows.png"))
img_label=Label(root)

def click(x):
    current=e.get()
    e.delete(0,END)
    e.insert(0,str(current)+str(x))

def backspace():
    e.delete(len(e.get())-1,END)

def tab():
    e.insert(END,'    ')

def space():
    e.insert(END,' ')

def enter():
    e.insert(END,'\n')

def caps():
    pass

def on_ctrl():
    b1=Button(frame1,text= '\u0D12',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D12'))
    b2=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b3=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b4=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b5=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b6=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b7=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b8=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b9=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b10=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b11=Button(frame1,text='\u0D66',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D66'))
    b12=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b13=Button(frame1,text='\u0D0B',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D0B'))
    bback=Button(frame1,text='Backspace',padx=15,pady=2,width=7,relief="raised",font=("Helvetica",10),command=backspace)

    btab=Button(frame2,text='Tab',padx=14,pady=2,width=7,relief="raised",font=("Helvetica",10),command=tab)
    b14=Button(frame2,text='\u0D13',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D13'))
    b15=Button(frame2,text='\u0D10',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D10'))
    b16=Button(frame2,text='\u0D06',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D06'))
    b17=Button(frame2,text='\u0D08',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D08'))
    b18=Button(frame2,text='\u0D0A',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D0A'))
    b19=Button(frame2,text='\u0D2D',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D2D'))
    b20=Button(frame2,text='\u0D19',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D19'))
    b21=Button(frame2,text='\u0D18',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D18'))
    b22=Button(frame2,text='\u0D27',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D27'))
    b23=Button(frame2,text='\u0D1D',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D1D'))
    b24=Button(frame2,text='\u0D22',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D22'))
    b25=Button(frame2,text='\u0D1E',padx=1,pady=2,width=4,font=("Helvetica",10),command=lambda:click('\u0D1E'))
    b2last=Button(frame2,text='\'',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\''))

    bcaps=Button(frame3,text='Caps Lock',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=caps)
    b26=Button(frame3,text='\u0D13',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D13'))
    b27=Button(frame3,text='\u0D0F',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D0F'))
    b28=Button(frame3,text='\u0D05',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D05'))
    b29=Button(frame3,text='\u0D07',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D07'))
    b30=Button(frame3,text='\u0D09',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D09'))
    b31=Button(frame3,text='\u0D2B',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D2B'))
    b32=Button(frame3,text='\u0D31',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D31'))
    b33=Button(frame3,text='\u0D16',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D16'))
    b34=Button(frame3,text='\u0D25',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D25'))
    b35=Button(frame3,text='\u0D1B',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D1B'))
    b36=Button(frame3,text='\u0D20',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D20'))
    benter=Button(frame3,text='Enter',padx=14,pady=2,width=8,relief="raised",font=("Helvetica",10),command=enter)
    
    bshift1=Button(frame4,text='Shift',padx=14,pady=2,width=9,relief="raised",font=("Helvetica",10),command=on_shift)
    b37=Button(frame4,text='\u0D0E',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D0E'))
    b38=Button(frame4,text='\u0D02',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D02'))
    b39=Button(frame4,text='\u0D23',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D23'))
    b40=Button(frame4,text='\u0D28',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D28'))
    b41=Button(frame4,text='\u0D34',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D34'))
    b42=Button(frame4,text='\u0D33',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D33'))
    b43=Button(frame4,text='\u0D36',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D36'))
    b44=Button(frame4,text='\u0D37',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D37'))
    b45=Button(frame4,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b46=Button(frame4,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    bshift2=Button(frame4,text='Shift',padx=13,pady=2,width=10,relief="raised",font=("Helvetica",10),command=on_shift)

    bctr=Button(frame5,text='Ctrl',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=off_ctrl)
    bwind=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt=Button(frame5,text='Alt',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_alt)
    bspace=Button(frame5,text='',padx=119,pady=2,width=5,relief="raised",font=("Helvetica",10),command=space)
    bctr2=Button(frame5,text='Ctrl',padx=14,pady=2,width=5,relief="raised",font=("Helvetica",10),command=off_ctrl)
    bwind2=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt2=Button(frame5,text='Alt',padx=13,pady=2,width=6,relief="raised",font=("Helvetica",10),command=on_alt)

    b1.grid(row=0,column=0)
    b2.grid(padx=1,row=0,column=1)
    b3.grid(padx=1,row=0,column=2)
    b4.grid(padx=1,row=0,column=3)
    b5.grid(padx=1,row=0,column=4)
    b6.grid(padx=1,row=0,column=5)
    b7.grid(padx=1,row=0,column=6)
    b8.grid(padx=1,row=0,column=7)
    b9.grid(padx=1,row=0,column=8)
    b10.grid(padx=1,row=0,column=9)
    b11.grid(padx=1,row=0,column=10)
    b12.grid(padx=1,row=0,column=11)
    b13.grid(padx=1,row=0,column=12)
    bback.grid(padx=1,row=0,column=14)

    btab.grid(row=0,column=0,columnspan=2)
    b14.grid(padx=1,row=0,column=2)
    b15.grid(padx=1,row=0,column=3)
    b16.grid(padx=1,row=0,column=4)
    b17.grid(padx=1,row=0,column=5)
    b18.grid(padx=1,row=0,column=6)
    b19.grid(padx=1,row=0,column=7)
    b20.grid(padx=1,row=0,column=8)
    b21.grid(padx=1,row=0,column=9)
    b22.grid(padx=1,row=0,column=10)
    b23.grid(padx=1,row=0,column=11)
    b24.grid(padx=1,row=0,column=12)
    b25.grid(padx=1,row=0,column=13)
    b2last.grid(padx=1,row=0,column=14)

    bcaps.grid(padx=1,row=0,column=0,columnspan=2)
    b26.grid(padx=1,row=0,column=2)
    b27.grid(padx=1,row=0,column=3)
    b28.grid(padx=1,row=0,column=4)
    b29.grid(padx=1,row=0,column=5)
    b30.grid(padx=1,row=0,column=6)
    b31.grid(padx=1,row=0,column=7)
    b32.grid(padx=1,row=0,column=8)
    b33.grid(padx=1,row=0,column=9)
    b34.grid(padx=1,row=0,column=10)
    b35.grid(padx=1,row=0,column=11)
    b36.grid(padx=1,row=0,column=12)
    benter.grid(padx=1,row=0,column=13,columnspan=2)

    bshift1.grid(padx=1,row=0,column=0,columnspan=2)
    b37.grid(padx=1,row=0,column=2)
    b38.grid(padx=1,row=0,column=3)
    b39.grid(padx=1,row=0,column=4)
    b40.grid(padx=1,row=0,column=5)
    b41.grid(padx=1,row=0,column=6)
    b42.grid(padx=1,row=0,column=7)
    b43.grid(padx=1,row=0,column=8)
    b44.grid(padx=1,row=0,column=9)
    b45.grid(padx=1,row=0,column=10)
    b46.grid(padx=1,row=0,column=11)
    bshift2.grid(padx=1,row=0,column=12,columnspan=2)

    bctr.grid(padx=1,row=0,column=0)
    bwind.grid(padx=1,row=0,column=1)
    balt.grid(padx=1,row=0,column=2)
    bspace.grid(padx=1,row=0,column=3,columnspan=3)
    bctr2.grid(padx=1,row=0,column=10)
    bwind2.grid(padx=1,row=0,column=11)
    balt2.grid(padx=1,row=0,column=12)
    
def off_ctrl():
    b1=Button(frame1,text='\u0D4A',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D4A'))
    b2=Button(frame1,text='\u0D67',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D67'))
    b3=Button(frame1,text='\u0D68',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D68'))
    b4=Button(frame1,text='\u0D69',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D69'))
    b5=Button(frame1,text='\u0D6A',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D6A'))
    b6=Button(frame1,text='\u0D6B',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D6B'))
    b7=Button(frame1,text='\u0D6C',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D6C'))
    b8=Button(frame1,text='\u0D6D',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D6D'))
    b9=Button(frame1,text='\u0D6E',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D6E'))
    b10=Button(frame1,text='\u0D6F',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D6F'))
    b11=Button(frame1,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b12=Button(frame1,text='\u0D03',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D03'))
    b13=Button(frame1,text='\u0D43',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D43'))
    bback=Button(frame1,text='Backspace',padx=15,pady=2,width=7,relief="raised",font=("Helvetica",10),command=backspace)

    btab=Button(frame2,text='Tab',padx=15,pady=2,width=7,relief="raised",font=("Helvetica",10),command=tab)
    b14=Button(frame2,text='\u0D4C',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D4C'))
    b15=Button(frame2,text='\u0D48',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D48'))
    b16=Button(frame2,text='\u0D3E',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click( '\u0D3E'))
    b17=Button(frame2,text='\u0D40',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D40'))
    b18=Button(frame2,text='\u0D42',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D42'))
    b19=Button(frame2,text='\u0D2C',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D2C'))
    b20=Button(frame2,text='\u0D39',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D39'))
    b21=Button(frame2,text='\u0D17',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D17'))
    b22=Button(frame2,text='\u0D26',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D26'))
    b23=Button(frame2,text='\u0D1C',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D1C'))
    b24=Button(frame2,text='\u0D21',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D21'))
    b25=Button(frame2,text='.',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('.'))
    b2last=Button(frame2,text='\'',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\''))

    bcaps=Button(frame3,text='Caps Lock',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=caps)
    b26=Button(frame3,text='\u0D4B',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D4B'))
    b27=Button(frame3,text='\u0D47',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D47'))
    b28=Button(frame3,text='\u0D4D',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D4D'))
    b29=Button(frame3,text='\u0D3F',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D3F'))
    b30=Button(frame3,text='\u0D41',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D41'))
    b31=Button(frame3,text='\u0D2A',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D2A'))
    b32=Button(frame3,text='\u0D30',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D30'))
    b33=Button(frame3,text='\u0D15',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D15'))
    b34=Button(frame3,text='\u0D24',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D24'))
    b35=Button(frame3,text='\u0D1A',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D1A'))
    b36=Button(frame3,text='\u0D1F',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D1F'))
    benter=Button(frame3,text='Enter',padx=14,pady=2,width=8,relief="raised",font=("Helvetica",10),command=enter)

    bshift1=Button(frame4,text='Shift',padx=14,pady=2,width=9,relief="raised",font=("Helvetica",10),command=on_shift)
    b37=Button(frame4,text='\u0D46',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D46'))
    b38=Button(frame4,text='\u0D02',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D02'))
    b39=Button(frame4,text='\u0D2E',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D2E'))
    b40=Button(frame4,text='\u0D28',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D28'))
    b41=Button(frame4,text='\u0D35',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D35'))
    b42=Button(frame4,text='\u0D32',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D32'))
    b43=Button(frame4,text='\u0D38',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D38'))
    b44=Button(frame4,text=',',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(','))
    b45=Button(frame4,text='.',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('.'))
    b46=Button(frame4,text='\u0D2F',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D2F'))
    bshift2=Button(frame4,text='Shift',padx=13,pady=2,width=10,relief="raised",font=("Helvetica",10),command=on_shift)

    bctr=Button(frame5,text='Ctrl',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_ctrl)
    bwind=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt=Button(frame5,text='Alt',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_alt)
    bspace=Button(frame5,text='',padx=119,pady=2,width=5,relief="raised",font=("Helvetica",10),command=space)
    bctr2=Button(frame5,text='Ctrl',padx=14,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_ctrl)
    bwind2=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt2=Button(frame5,text='Alt',padx=13,pady=2,width=6,relief="raised",font=("Helvetica",10),command=on_alt)

    b1.grid(row=0,column=0)
    b2.grid(padx=1,row=0,column=1)
    b3.grid(padx=1,row=0,column=2)
    b4.grid(padx=1,row=0,column=3)
    b5.grid(padx=1,row=0,column=4)
    b6.grid(padx=1,row=0,column=5)
    b7.grid(padx=1,row=0,column=6)
    b8.grid(padx=1,row=0,column=7)
    b9.grid(padx=1,row=0,column=8)
    b10.grid(padx=1,row=0,column=9)
    b11.grid(padx=1,row=0,column=10)
    b12.grid(padx=1,row=0,column=11)
    b13.grid(padx=1,row=0,column=12)
    bback.grid(padx=1,row=0,column=14)

    btab.grid(row=0,column=0,columnspan=2)
    b14.grid(padx=1,row=0,column=2)
    b15.grid(padx=1,row=0,column=3)
    b16.grid(padx=1,row=0,column=4)
    b17.grid(padx=1,row=0,column=5)
    b18.grid(padx=1,row=0,column=6)
    b19.grid(padx=1,row=0,column=7)
    b20.grid(padx=1,row=0,column=8)
    b21.grid(padx=1,row=0,column=9)
    b22.grid(padx=1,row=0,column=10)
    b23.grid(padx=1,row=0,column=11)
    b24.grid(padx=1,row=0,column=12)
    b25.grid(padx=1,row=0,column=13)
    b2last.grid(padx=1,row=0,column=14)

    bcaps.grid(padx=1,row=0,column=0,columnspan=2)
    b26.grid(padx=1,row=0,column=2)
    b27.grid(padx=1,row=0,column=3)
    b28.grid(padx=1,row=0,column=4)
    b29.grid(padx=1,row=0,column=5)
    b30.grid(padx=1,row=0,column=6)
    b31.grid(padx=1,row=0,column=7)
    b32.grid(padx=1,row=0,column=8)
    b33.grid(padx=1,row=0,column=9)
    b34.grid(padx=1,row=0,column=10)
    b35.grid(padx=1,row=0,column=11)
    b36.grid(padx=1,row=0,column=12)
    benter.grid(padx=1,row=0,column=13,columnspan=2)

    bshift1.grid(padx=1,row=0,column=0,columnspan=2)
    b37.grid(padx=1,row=0,column=2)
    b38.grid(padx=1,row=0,column=3)
    b39.grid(padx=1,row=0,column=4)
    b40.grid(padx=1,row=0,column=5)
    b41.grid(padx=1,row=0,column=6)
    b42.grid(padx=1,row=0,column=7)
    b43.grid(padx=1,row=0,column=8)
    b44.grid(padx=1,row=0,column=9)
    b45.grid(padx=1,row=0,column=10)
    b46.grid(padx=1,row=0,column=11)
    bshift2.grid(padx=1,row=0,column=12,columnspan=2)

    bctr.grid(padx=1,row=0,column=0)
    bwind.grid(padx=1,row=0,column=1)
    balt.grid(padx=1,row=0,column=2)
    bspace.grid(padx=1,row=0,column=3,columnspan=3)
    bctr2.grid(padx=1,row=0,column=10)
    bwind2.grid(padx=1,row=0,column=11)
    balt2.grid(padx=1,row=0,column=12)

def on_shift():
    b1=Button(frame1,text='~',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('~'))
    b2=Button(frame1,text='1',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('1'))
    b3=Button(frame1,text='2',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('2'))
    b4=Button(frame1,text='3',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('3'))
    b5=Button(frame1,text='4',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('4'))
    b6=Button(frame1,text='5',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('5'))
    b7=Button(frame1,text='6',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('6'))
    b8=Button(frame1,text='7',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('7'))
    b9=Button(frame1,text='8',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('8'))
    b10=Button(frame1,text='9',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('9'))
    b11=Button(frame1,text='0',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('0'))
    b12=Button(frame1,text='-',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('-'))
    b13=Button(frame1,text='=',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('='))
    bback=Button(frame1,text='Backspace',padx=15,pady=2,width=7,relief="raised",font=("Helvetica",10),command=backspace)

    btab=Button(frame2,text='Tab',padx=15,pady=2,width=7,relief="raised",font=("Helvetica",10),command=tab)
    b14=Button(frame2,text='\u0D71',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D71'))
    b15=Button(frame2,text='\u0D7A',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D7A'))
    b16=Button(frame2,text='\u0D7C',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D7C'))
    b17=Button(frame2,text='\u0D7D',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D7D'))
    b18=Button(frame2,text='\u0D7E',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D7E'))
    b19=Button(frame2,text='\u0D7F',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\u0D7F'))
    b20=Button(frame2,text='+',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('+'))
    b21=Button(frame2,text='[',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('['))
    b22=Button(frame2,text=']',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(']'))
    b23=Button(frame2,text='{',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('{'))
    b24=Button(frame2,text='}',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('}'))
    b25=Button(frame2,text='|',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('|'))
    b2last=Button(frame2,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))

    bcaps=Button(frame3,text='Caps Lock',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=caps)
    b26=Button(frame3,text='!',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('!'))
    b27=Button(frame3,text='@',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('@'))
    b28=Button(frame3,text='#',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('#'))
    b29=Button(frame3,text='$',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('$'))
    b30=Button(frame3,text='%',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('%'))
    b31=Button(frame3,text='^',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('^'))
    b32=Button(frame3,text='&',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('&'))
    b33=Button(frame3,text='*',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('*'))
    b34=Button(frame3,text='(',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('('))
    b35=Button(frame3,text=')',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(')'))
    b36=Button(frame3,text=':',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(':'))
    benter=Button(frame3,text='Enter',padx=14,pady=2,width=8,relief="raised",font=("Helvetica",10),command=enter)

    bshift1=Button(frame4,text='Shift',padx=14,pady=2,width=9,relief="raised",font=("Helvetica",10),command=off_ctrl)
    b37=Button(frame4,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b38=Button(frame4,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b39=Button(frame4,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    b40=Button(frame4,text='/',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('/'))
    b41=Button(frame4,text='?',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('?'))
    b42=Button(frame4,text='<',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('<'))
    b43=Button(frame4,text='>',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('>'))
    b44=Button(frame4,text=',',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(','))
    b45=Button(frame4,text='.',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('.'))
    b46=Button(frame4,text=';',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(';'))
    bshift2=Button(frame4,text='Shift',padx=13,pady=2,width=10,relief="raised",font=("Helvetica",10),command=off_ctrl)

    bctr=Button(frame5,text='Ctrl',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_ctrl)
    bwind=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt=Button(frame5,text='Alt',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_alt)
    bspace=Button(frame5,text='',padx=119,pady=2,width=5,relief="raised",font=("Helvetica",10),command=space)
    bctr2=Button(frame5,text='Ctrl',padx=14,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_ctrl)
    bwind2=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt2=Button(frame5,text='Alt',padx=13,pady=2,width=6,relief="raised",font=("Helvetica",10),command=on_alt)

    b1.grid(row=0,column=0)
    b2.grid(padx=1,row=0,column=1)
    b3.grid(padx=1,row=0,column=2)
    b4.grid(padx=1,row=0,column=3)
    b5.grid(padx=1,row=0,column=4)
    b6.grid(padx=1,row=0,column=5)
    b7.grid(padx=1,row=0,column=6)
    b8.grid(padx=1,row=0,column=7)
    b9.grid(padx=1,row=0,column=8)
    b10.grid(padx=1,row=0,column=9)
    b11.grid(padx=1,row=0,column=10)
    b12.grid(padx=1,row=0,column=11)
    b13.grid(padx=1,row=0,column=12)
    bback.grid(padx=1,row=0,column=14)

    btab.grid(row=0,column=0,columnspan=2)
    b14.grid(padx=1,row=0,column=2)
    b15.grid(padx=1,row=0,column=3)
    b16.grid(padx=1,row=0,column=4)
    b17.grid(padx=1,row=0,column=5)
    b18.grid(padx=1,row=0,column=6)
    b19.grid(padx=1,row=0,column=7)
    b20.grid(padx=1,row=0,column=8)
    b21.grid(padx=1,row=0,column=9)
    b22.grid(padx=1,row=0,column=10)
    b23.grid(padx=1,row=0,column=11)
    b24.grid(padx=1,row=0,column=12)
    b25.grid(padx=1,row=0,column=13)
    b2last.grid(padx=1,row=0,column=14)

    bcaps.grid(padx=1,row=0,column=0,columnspan=2)
    b26.grid(padx=1,row=0,column=2)
    b27.grid(padx=1,row=0,column=3)
    b28.grid(padx=1,row=0,column=4)
    b29.grid(padx=1,row=0,column=5)
    b30.grid(padx=1,row=0,column=6)
    b31.grid(padx=1,row=0,column=7)
    b32.grid(padx=1,row=0,column=8)
    b33.grid(padx=1,row=0,column=9)
    b34.grid(padx=1,row=0,column=10)
    b35.grid(padx=1,row=0,column=11)
    b36.grid(padx=1,row=0,column=12)
    benter.grid(padx=1,row=0,column=13,columnspan=2)

    bshift1.grid(padx=1,row=0,column=0,columnspan=2)
    b37.grid(padx=1,row=0,column=2)
    b38.grid(padx=1,row=0,column=3)
    b39.grid(padx=1,row=0,column=4)
    b40.grid(padx=1,row=0,column=5)
    b41.grid(padx=1,row=0,column=6)
    b42.grid(padx=1,row=0,column=7)
    b43.grid(padx=1,row=0,column=8)
    b44.grid(padx=1,row=0,column=9)
    b45.grid(padx=1,row=0,column=10)
    b46.grid(padx=1,row=0,column=11)
    bshift2.grid(padx=1,row=0,column=12,columnspan=2)

    bctr.grid(padx=1,row=0,column=0)
    bwind.grid(padx=1,row=0,column=1)
    balt.grid(padx=1,row=0,column=2)
    bspace.grid(padx=1,row=0,column=3,columnspan=3)
    bctr2.grid(padx=1,row=0,column=10)
    bwind2.grid(padx=1,row=0,column=11)
    balt2.grid(padx=1,row=0,column=12)

def on_alt():
    b1=Button(frame1,text='Esc',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('Esc'))
    b2=Button(frame1,text='F1',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F1'))
    b3=Button(frame1,text='F2',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F2'))
    b4=Button(frame1,text='F3',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F3'))
    b5=Button(frame1,text='F4',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F4'))
    b6=Button(frame1,text='F5',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F5'))
    b7=Button(frame1,text='F6',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F6'))
    b8=Button(frame1,text='F7',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F7'))
    b9=Button(frame1,text='F8',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F8'))
    b10=Button(frame1,text='F9',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F9'))
    b11=Button(frame1,text='F10',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F10'))
    b12=Button(frame1,text='F11',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F11'))
    b13=Button(frame1,text='F12',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F12'))
    bback=Button(frame1,text='Backspace',padx=15,pady=2,width=7,relief="raised",font=("Helvetica",10),command=backspace)

    btab=Button(frame2,text='Tab',padx=15,pady=2,width=7,relief="raised",font=("Helvetica",10),command=tab)
    b14=Button(frame2,text='Q',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('Q'))
    b15=Button(frame2,text='W',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('W'))
    b16=Button(frame2,text='E',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('E'))
    b17=Button(frame2,text='R',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('R'))
    b18=Button(frame2,text='T',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('T'))
    b19=Button(frame2,text='Y',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('Y'))
    b20=Button(frame2,text='U',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('U'))
    b21=Button(frame2,text='I',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('I'))
    b22=Button(frame2,text='O',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('O'))
    b23=Button(frame2,text='P',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('P'))
    b24=Button(frame2,text='[',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('['))
    b25=Button(frame2,text=']',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(']'))
    b2last=Button(frame2,text='\'',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('\''))

    bcaps=Button(frame3,text='Caps Lock',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=caps)
    b26=Button(frame3,text='A',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('A'))
    b27=Button(frame3,text='S',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('S'))
    b28=Button(frame3,text='D',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('D'))
    b29=Button(frame3,text='F',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('F'))
    b30=Button(frame3,text='G',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('G'))
    b31=Button(frame3,text='H',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('H'))
    b32=Button(frame3,text='J',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('J'))
    b33=Button(frame3,text='K',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('K'))
    b34=Button(frame3,text='L',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('L'))
    b35=Button(frame3,text=';',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(';'))
    b36=Button(frame3,text='',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(''))
    benter=Button(frame3,text='Enter',padx=14,pady=2,width=8,relief="raised",font=("Helvetica",10),command=enter)

    bshift1=Button(frame4,text='Shift',padx=14,pady=2,width=9,relief="raised",font=("Helvetica",10),command=on_shift)
    b37=Button(frame4,text='Z',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('Z'))
    b38=Button(frame4,text='X',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('X'))
    b39=Button(frame4,text='C',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('C'))
    b40=Button(frame4,text='V',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('V'))
    b41=Button(frame4,text='B',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('B'))
    b42=Button(frame4,text='N',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('N'))
    b43=Button(frame4,text='M',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('M'))
    b44=Button(frame4,text=',',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click(','))
    b45=Button(frame4,text='.',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('.'))
    b46=Button(frame4,text='/',padx=1,pady=2,width=4,relief="raised",font=("Helvetica",10),command=lambda:click('/'))
    bshift2=Button(frame4,text='Shift',padx=13,pady=2,width=10,relief="raised",font=("Helvetica",10),command=on_shift)

    bctr=Button(frame5,text='Ctrl',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_ctrl)
    bwind=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt=Button(frame5,text='Alt',padx=15,pady=2,width=5,relief="raised",font=("Helvetica",10),command=off_ctrl)
    bspace=Button(frame5,text='',padx=119,pady=2,width=5,relief="raised",font=("Helvetica",10),command=space)
    bctr2=Button(frame5,text='Ctrl',padx=14,pady=2,width=5,relief="raised",font=("Helvetica",10),command=on_ctrl)
    bwind2=Button(frame5,image=img,padx=15,pady=2,width=20,relief="raised",font=("Helvetica",10),command=caps)
    balt2=Button(frame5,text='Alt',padx=13,pady=2,width=6,relief="raised",font=("Helvetica",10),command=off_ctrl)

    b1.grid(row=0,column=0)
    b2.grid(padx=1,row=0,column=1)
    b3.grid(padx=1,row=0,column=2)
    b4.grid(padx=1,row=0,column=3)
    b5.grid(padx=1,row=0,column=4)
    b6.grid(padx=1,row=0,column=5)
    b7.grid(padx=1,row=0,column=6)
    b8.grid(padx=1,row=0,column=7)
    b9.grid(padx=1,row=0,column=8)
    b10.grid(padx=1,row=0,column=9)
    b11.grid(padx=1,row=0,column=10)
    b12.grid(padx=1,row=0,column=11)
    b13.grid(padx=1,row=0,column=12)
    bback.grid(padx=1,row=0,column=14)

    btab.grid(row=0,column=0,columnspan=2)
    b14.grid(padx=1,row=0,column=2)
    b15.grid(padx=1,row=0,column=3)
    b16.grid(padx=1,row=0,column=4)
    b17.grid(padx=1,row=0,column=5)
    b18.grid(padx=1,row=0,column=6)
    b19.grid(padx=1,row=0,column=7)
    b20.grid(padx=1,row=0,column=8)
    b21.grid(padx=1,row=0,column=9)
    b22.grid(padx=1,row=0,column=10)
    b23.grid(padx=1,row=0,column=11)
    b24.grid(padx=1,row=0,column=12)
    b25.grid(padx=1,row=0,column=13)
    b2last.grid(padx=1,row=0,column=14)

    bcaps.grid(padx=1,row=0,column=0,columnspan=2)
    b26.grid(padx=1,row=0,column=2)
    b27.grid(padx=1,row=0,column=3)
    b28.grid(padx=1,row=0,column=4)
    b29.grid(padx=1,row=0,column=5)
    b30.grid(padx=1,row=0,column=6)
    b31.grid(padx=1,row=0,column=7)
    b32.grid(padx=1,row=0,column=8)
    b33.grid(padx=1,row=0,column=9)
    b34.grid(padx=1,row=0,column=10)
    b35.grid(padx=1,row=0,column=11)
    b36.grid(padx=1,row=0,column=12)
    benter.grid(padx=1,row=0,column=13,columnspan=2)

    bshift1.grid(padx=1,row=0,column=0,columnspan=2)
    b37.grid(padx=1,row=0,column=2)
    b38.grid(padx=1,row=0,column=3)
    b39.grid(padx=1,row=0,column=4)
    b40.grid(padx=1,row=0,column=5)
    b41.grid(padx=1,row=0,column=6)
    b42.grid(padx=1,row=0,column=7)
    b43.grid(padx=1,row=0,column=8)
    b44.grid(padx=1,row=0,column=9)
    b45.grid(padx=1,row=0,column=10)
    b46.grid(padx=1,row=0,column=11)
    bshift2.grid(padx=1,row=0,column=12,columnspan=2)

    bctr.grid(padx=1,row=0,column=0)
    bwind.grid(padx=1,row=0,column=1)
    balt.grid(padx=1,row=0,column=2)
    bspace.grid(padx=1,row=0,column=3,columnspan=3)
    bctr2.grid(padx=1,row=0,column=10)
    bwind2.grid(padx=1,row=0,column=11)
    balt2.grid(padx=1,row=0,column=12)



off_ctrl()

root.mainloop()
